
####################################################################################
# Generated by Vivado 2024.2 built on 'Fri Nov 08 22:35:27 MST 2024' by 'xbuild'
# Command Used: write_xdc -force C:/Users/shubh/logic_gates/constrs_1.xdc
####################################################################################


# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
